apiVersion: v1
kind: Service
metadata:
  name: flaskapp-api
spec:
  selector:
    app.kubernetes.io/name: flaskpp-api
  ports:
    - name: "5153"
      protocol: TCP
      port: 5153
      targetPort: 5153
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp-api
  labels:
    name: flaskapp-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: flaskapp-api
  template:
    metadata:
      labels:
        service: flaskapp-api
    spec:
      containers:
        - name: flaskapp-api
          image: 328287431813.dkr.ecr.us-east-1.amazonaws.com/daily-usage-registry:12
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health_check
              port: 5153
            initialDelaySeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: "/readiness_check"
              port: 5153
            initialDelaySeconds: 5
            timeoutSeconds: 5
          env:
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_USERNAME
            - name: DB_PASSWORD
              value: rJ6lPsG58r  # Directly assign the password value
            - name: DB_HOST
              value: my-pos-postgresql
      restartPolicy: Always
